version: "3"

services:
  seaside:
    build:
      context: .
      dockerfile: ./containers/seaside/Dockerfile
    ports:
      - 8000:8000
    # command: ./target/release/seaside

  menel:
    build:
      context: .
      dockerfile: ./containers/menel/Dockerfile
    ports:
      - 8080:8080
    # command: ./target/release/menel
