apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: menel-api
  name: menel-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menel-api
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: menel-api
    spec:
      containers:
        - image: 192.168.0.1:5000/menel-api:v1
          name: menel-api
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: menel-api-svc

spec:
  selector:
    app: menel-api

  ports:
    - name: http
      port: 8080
      nodePort: 30088

  type: NodePort
