logLevel = "INFO"
defaultEntryPoints = ["http"]

[web]
  address = ":5555"

[entryPoints]
  [entryPoints.http]
  address = ":8888"

[file]
[backends]
  [backends.rust]
    [backends.rust.servers.server1]
      url = "http://web:8000"

[frontends]
  [frontends.rust]
    backend = "rust"
    passHostHeader = true
    [frontends.rust.headers]
      HostsProxyHeaders = ['X-CSRFToken']

